Repository mash-up-kr/weQuiz-iOS, pull requests merged in 2023-07, with the labels that each got.

#48 문제 만들기 뷰 UI (#27, #14)
  Projects/Quiz/Targets/QuizKit/Sources/QuestionModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/AddAnswerView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Answer/AlphabetCircleView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Answer/InputAnswerView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Extensions/AnimatableModifier.swift
  Projects/Quiz/Targets/QuizUI/Sources/Extensions/View+.swift
  Projects/Quiz/Targets/QuizUI/Sources/MakeQuizView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Question/AddAnswerButtonView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Question/MultipleSelectionView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Question/QuestionView.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuestionView.swift
Labels: :white_check_mark: Accepted, :hatched_chick: sohy

#43 :bulb: Home 뷰에 DesignSystem 컴퍼넌트 적용 (#9)
  Projects/Home/Targets/Home/Sources/HomeApp.swift
  Projects/Home/Targets/HomeUI/Sources/Model/QuestionGroup.swift
  Projects/Home/Targets/HomeUI/Sources/View/FriendsList.swift
  Projects/Home/Targets/HomeUI/Sources/View/FriendsRow.swift
  Projects/Home/Targets/HomeUI/Sources/View/Home.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionGroupRow.swift
Labels: :octopus: ㅊ, :clock1: In Review

#55 문제 만들기 - 시험지 완성
  Projects/Quiz/Targets/QuizUI/Sources/Extensions/ActivityViewController.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizCompletion/QuizCompletionView.swift
Labels: :white_check_mark: Accepted, :hatched_chick: sohy

#56 [DA] Gradient Color 추가 및 WQGradientProgressBar 구현
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Colors.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQGradientProgressBar.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/View+Gradient.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ColorPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQGradientProgressBarPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#59 💡 QuestionDetailView UI 구현
  Projects/Home/Targets/Home/Resources/Assets.xcassets/share-social.imageset/Contents.json
  Projects/Home/Targets/Home/Resources/Assets.xcassets/share-social.imageset/share-social.pdf
  Projects/Home/Targets/Home/Resources/Assets.xcassets/trash.imageset/Contents.json
  Projects/Home/Targets/Home/Resources/Assets.xcassets/trash.imageset/trash.pdf
  Projects/Home/Targets/HomeUI/Sources/Model/QuestionGroup.swift
  Projects/Home/Targets/HomeUI/Sources/View/AlphabetCircleView.swift
  Projects/Home/Targets/HomeUI/Sources/View/AnswerListRow.swift
  Projects/Home/Targets/HomeUI/Sources/View/AnswerPercentView.swift
  Projects/Home/Targets/HomeUI/Sources/View/FriendsList.swift
  Projects/Home/Targets/HomeUI/Sources/View/FriendsRow.swift
  Projects/Home/Targets/HomeUI/Sources/View/Home.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionDetail.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionDetailRow.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionGroupList.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionGroupRow.swift
Labels: :octopus: ㅊ, :white_check_mark: Accepted

#62 Quiz - 문제 만들기 세부 기능 #49
  Projects/Quiz/Targets/QuizKit/Sources/QuestionViewModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/MakeQuizView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Question/QuestionView.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizCompletion/QuizCompletionView.swift
Labels: :white_check_mark: Accepted, :hatched_chick: sohy

#66 💡 Home - QuestionDetailView Flip Card 적용
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendsList.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendsRow.swift
  Projects/Home/Targets/HomeUI/Sources/Home/Home.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomeViewModel.swift
  Projects/Home/Targets/HomeUI/Sources/Network/HomeService.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/Explain.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/Friend.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/Profile.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/QuestionGroup.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AlphabetCircleView.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerListContainer.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerListRow.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerPercentView.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/QuestionDetail.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionGroup/QuestionGroupList.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionGroup/QuestionGroupRow.swift
Labels: :octopus: ㅊ, :bulb: TODO, :white_check_mark: Accepted

#71 문제 뷰 모델 수정
  Projects/Quiz/Targets/QuizKit/Sources/QuestionModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/QuestionViewModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/MakeQuizView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Question/QuestionView.swift
Labels: :white_check_mark: Accepted, :hatched_chick: sohy

#74 :recycle: Home - 디자인에 맞춰 View 재셋팅
  Projects/Home/Targets/Home/Resources/Assets.xcassets/BronzeGrade.imageset/BronzeGrade.pdf
  Projects/Home/Targets/Home/Resources/Assets.xcassets/BronzeGrade.imageset/Contents.json
  Projects/Home/Targets/Home/Resources/Assets.xcassets/GoldGrade.imageset/Contents.json
  Projects/Home/Targets/Home/Resources/Assets.xcassets/GoldGrade.imageset/GoldGrade.pdf
  Projects/Home/Targets/Home/Resources/Assets.xcassets/NoRank.imageset/Contents.json
  Projects/Home/Targets/Home/Resources/Assets.xcassets/NoRank.imageset/NoRank.pdf
  Projects/Home/Targets/Home/Resources/Assets.xcassets/SilverGrade.imageset/Contents.json
  Projects/Home/Targets/Home/Resources/Assets.xcassets/SilverGrade.imageset/SilverGrade.pdf
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendsList.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendsRow.swift
  Projects/Home/Targets/HomeUI/Sources/Home/Home.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerListContainer.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionGroup/QuestionGroupList.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionGroup/QuestionGroupRow.swift
Labels: :octopus: ㅊ, :white_check_mark: Accepted

#75 :recycle: 문제 만들기 - model, viewModel 이름 수정 (#49)
  Projects/Quiz/Targets/QuizKit/Sources/Models/MakeQuizModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/ViewModels/MakeQuizViewModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/Answer/InputAnswerView.swift
  Projects/Quiz/Targets/QuizUI/Sources/MakeQuizView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Question/QuestionView.swift
Labels: :white_check_mark: Accepted

#79 :bulb: 문제 풀기 완료
  Projects/Quiz/Targets/QuizKit/Sources/Models/QuizResultModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultRankView.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultView.swift
Labels: :white_check_mark: Accepted

#63 [DA] DesignSystem 2차 QA 수정사항 반영
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/icons/share/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/icons/share/share_fill_gray_24.imageset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/icons/share/share_fill_gray_24.imageset/share_fill_gray_24.pdf
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/icons/trash_can/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/icons/trash_can/trash_can_fill_gray_24.imageset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/icons/trash_can/trash_can_fill_gray_24.imageset/trash_can_fill_gray_24.pdf
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQButton.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQModal.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Icon.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/IconPreview.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#69 [DA] feat: 메인 앱 연결 (#65)
  Projects/DesignSystem/Project.swift
  Projects/Main/Project.swift
  Projects/Main/Targets/Main/SupportingFiles/Main-Info.plist
  Projects/Main/Targets/MainKit/Sources/MainKit.swift
  Projects/Main/Targets/MainUI/Sources/ContentView.swift
  Projects/Quiz/Targets/Quiz/SupportingFiles/Quiz-Info.plist
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  WeQuiz-iOS.xcworkspace/xcshareddata/xcschemes/WeQuiz-iOS-Workspace.xcscheme
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#80 :recycle: Home - ViewModel 수정
  Projects/Home/Targets/HomeKit/Sources/Network/HomeService.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendsList.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendsRow.swift
  Projects/Home/Targets/HomeUI/Sources/Home/Home.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomeViewModel.swift
  Projects/Home/Targets/HomeUI/Sources/Model/FriendRankGroupModel.swift
  Projects/Home/Targets/HomeUI/Sources/Model/MyInfoModel.swift
  Projects/Home/Targets/HomeUI/Sources/Model/QuestionDetailModel.swift
  Projects/Home/Targets/HomeUI/Sources/Model/QuestionGroupModel.swift
  Projects/Home/Targets/HomeUI/Sources/Model/QuestionStatisticModel.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/Explain.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/Friend.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/Profile.swift
  Projects/Home/Targets/HomeUI/Sources/Network/Model/QuestionGroup.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AlphabetCircleView.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerListContainer.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerListRow.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/AnswerPercentView.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionDetail/QuestionDetail.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionGroup/QuestionGroupList.swift
  Projects/Home/Targets/HomeUI/Sources/QuestionGroup/QuestionGroupRow.swift
Labels: :clock1: In Review

#85 퀴즈 풀기 - 통신 연결
  Projects/Quiz/Targets/QuizKit/Sources/Models/QuizResultModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/Models/SolveQuizModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/Network/RequestModel/QuizRequestModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/Network/ResponseModel/QuizResponseModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/Network/Service/QuizAPI.swift
  Projects/Quiz/Targets/QuizKit/Sources/Network/Service/QuizService.swift
  Projects/Quiz/Targets/QuizKit/Sources/ViewModels/SolveQuizViewModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultConfigurator.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultDataStore.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultInteractor.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultPresenter.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultView.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/View+/QuizResultRankView.swift
  Projects/Quiz/Targets/QuizUI/Sources/Solve/SolveQuizView.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizConfigurator.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizDataStore.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizInteractor.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizPresenter.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizView.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/View+/SolveQuizAnswerView.swift
Labels: :white_check_mark: Accepted

#86 [DA] 서버 응답모델 수정
  Projects/Authentication/Targets/AuthenticationKit/Sources/Service/AuthenticationAPI.swift
  Projects/Authentication/Targets/AuthenticationKit/Sources/Service/AuthenticationService.swift
  Projects/Authentication/Targets/AuthenticationKit/Sources/VerificationCode/VerificationCodeInputInteractor.swift
  Projects/Core/Targets/CoreKit/Sources/Network/Networking.swift
  Projects/Core/Targets/CoreKit/Sources/ResponseModel/BaseResponseModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/Network/ResponseModel/QuizResponseModel.swift
  Projects/Quiz/Targets/QuizKit/Sources/Network/Service/QuizService.swift
  Projects/Quiz/Targets/QuizUI/Sources/MakeQuiz/MakeQuizInteractor.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultInteractor.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizInteractor.swift
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#88 퀴즈 - 세부기능
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_1.imageset/Contents.json
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_1.imageset/quizResult_1.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_1.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_2.imageset/Contents.json
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_2.imageset/quizResult_2.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_2.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_3.imageset/Contents.json
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_3.imageset/quizResult_3.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_3.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_4.imageset/Contents.json
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_4.imageset/quizResult_4.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_4.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_5.imageset/Contents.json
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_5.imageset/quizResult_5.png
  Projects/Quiz/Targets/Quiz/Resources/Assets.xcassets/quizResult_5.png
  Projects/Quiz/Targets/QuizKit/Sources/Models/QuizResultModel.swift
  Projects/Quiz/Targets/QuizUI/Sources/QuizResult/QuizResultView.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizDataStore.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizPresenter.swift
  Projects/Quiz/Targets/QuizUI/Sources/SolveQuiz/SolveQuizView.swift
Labels: :white_check_mark: Accepted
