Repository mash-up-kr/weQuiz-iOS, pull requests merged in 2023-06, with the labels that each got.

#15 [D2] Icon 구현 및 Preview 작성
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/Image+Icon.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Icon.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/IconPreview.swift
Labels: :whale: szzang, :white_check_mark: Accepted, :ticket: D2

#16 [D2] Colors 구현 및 Preview 작성
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g1.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g2.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g3.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g4.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g5.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g6.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g7.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g8.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g9.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/opacity/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/opacity/dimed.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/alert.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/disabled.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/main.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Colors.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/Color+Colors.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ColorPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
Labels: :whale: szzang, :white_check_mark: Accepted, :ticket: D2

#17 [DA] DesignSystem -> develop
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g1.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g2.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g3.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g4.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g5.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g6.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g7.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g8.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/extendedgray/g9.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/opacity/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/opacity/dimed.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/alert.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/disabled.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/Assets.xcassets/colors/semantic/main.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystem/Resources/LaunchScreen.storyboard
  Projects/DesignSystem/Targets/DesignSystem/Resources/Pretendard/PretendardJP-Bold.otf
  Projects/DesignSystem/Targets/DesignSystem/Resources/Pretendard/PretendardJP-Medium.otf
  Projects/DesignSystem/Targets/DesignSystem/Resources/Pretendard/PretendardJP-Regular.otf
  Projects/DesignSystem/Targets/DesignSystem/Resources/Pretendard/PretendardJP-SemiBold.otf
  Projects/DesignSystem/Targets/DesignSystem/SupportingFiles/DesignSystem-Info.plist
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Colors.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/DesignSystemKit.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/Color+Colors.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/Font+Typography.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/Image+Icon.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Icon.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Pretendard.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Typography.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ColorPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/IconPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/TypographyPreview.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#18 [DA] 다른 타겟에서 DesignSystem 사용할 수 있도록 변경
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g1.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g2.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g3.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g4.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g5.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g6.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g7.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g8.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g9.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/opacity/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/opacity/dimed.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/semantic/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/semantic/alert.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/semantic/disabled.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/semantic/main.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Pretendard/PretendardJP-Bold.otf
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Pretendard/PretendardJP-Medium.otf
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Pretendard/PretendardJP-Regular.otf
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Pretendard/PretendardJP-SemiBold.otf
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/DesignSystemKit.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#19 [DA] WQButton 구현 및 Preview 작성
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQButton.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/ComponentPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQButtonPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#20 [DA] WQSearchBar, WQTopBar 구현
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQSearchBar.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQTopBar.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/View+ClearButton.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/ComponentPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQSearchBarPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQTopBarPreview.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#23 [DA] Project 파일 수정
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#25 [DA] WQModal 구현
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQButton.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQModal.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/View+Modal.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/ComponentPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQModalPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#31 [DA] 디자인 시스템 Gray Color Hex Update
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/Secondary/s1.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g1.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g2.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g3.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g4.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g5.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g6.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g7.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g8.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/extendedgray/g9.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/semantic/main.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Colors.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#26 :sparkles: Home뷰 기본 틀 구현 (#9, #10, #11, #12)
  Projects/Home/Targets/Home/Sources/HomeApp.swift
  Projects/Home/Targets/HomeUI/Sources/ContentView.swift
  Projects/Home/Targets/HomeUI/Sources/Model/Explain.swift
  Projects/Home/Targets/HomeUI/Sources/Model/Friend.swift
  Projects/Home/Targets/HomeUI/Sources/Model/Profile.swift
  Projects/Home/Targets/HomeUI/Sources/Model/QuestionGroup.swift
  Projects/Home/Targets/HomeUI/Sources/View/FriendsList.swift
  Projects/Home/Targets/HomeUI/Sources/View/FriendsRow.swift
  Projects/Home/Targets/HomeUI/Sources/View/Home.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionDetail.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionDetailRow.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionGroupList.swift
  Projects/Home/Targets/HomeUI/Sources/View/QuestionGroupRow.swift
  Projects/Home/Targets/HomeUI/Sources/ViewModel/HomeViewModel.swift
Labels: :octopus: ㅊ, :white_check_mark: Accepted

#32 [DA] WQInputField 컴포넌트 구현
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQInputField.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQTextField/WQLimitCharacterTextField.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQTextField/WQPhoneNumberTextField.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQTextField/WQVerificationCodeTextField.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQInputFieldPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#39 [DA] button height 수정(#37)
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQButton.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#41 [DA] SearchBar 수정(#40)
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQSearchBar.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#42 [DA] WQToast 구현 (#8)
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQToast.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/View+Toast.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQToastPreview.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/ContentView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#45 [DA] 로그인/회원가입 UI 및 Navigation 구현
  Projects/Authentication/Targets/Authentication/Sources/AuthenticationApp.swift
  Projects/Authentication/Targets/Authentication/SupportingFiles/Authentication-Info.plist
  Projects/Authentication/Targets/AuthenticationUI/Sources/AuthenticationRouter.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/ContentView.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/OnboardingView.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/Routing/Extensions/View+Modal.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/Routing/Router.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/Routing/RoutingView.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/Routing/ViewSpec.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/SignUp/PhoneNumberInputView.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/SignUp/SignUpFinishView.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/SignUp/UserInformationInputView.swift
  Projects/Authentication/Targets/AuthenticationUI/Sources/SignUp/VerificationCodeInputView.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQButton.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQInputField.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Extensions/View+ClearButton.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted
