Repository mash-up-kr/weQuiz-iOS, pull requests merged in 2023-08, with the labels that each got.

#96 [DA] 💡 fastlane match 적용
  Matchfile
  ci_scripts/ci_post_clone.sh
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#97 :recycle: 퀴즈 만들기 - UI QA (#89)
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizView.swift
  Projects/WeQuiz/Sources/Quiz/Question/QuestionView.swift
Labels: :white_check_mark: Accepted

#101 퀴즈 - UI QA
  Projects/WeQuiz/Resources/Assets.xcassets/img_success.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/img_success.imageset/img_success.png
  Projects/WeQuiz/Resources/Assets.xcassets/img_success.png
  Projects/WeQuiz/Sources/Quiz/Question/QuestionView.swift
  Projects/WeQuiz/Sources/Quiz/QuizCompletion/QuizCompletionView.swift
Labels: :white_check_mark: Accepted

#102 Feature/ws/qa
  Projects/DesignSystem/Derived/Sources/TuistAssets+DesignSystemKit.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Home/BronzeGrade.imageset/BronzeGrade.pdf
  Projects/WeQuiz/Resources/Assets.xcassets/Home/BronzeGrade.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/GoldGrade.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/GoldGrade.imageset/GoldGrade.pdf
  Projects/WeQuiz/Resources/Assets.xcassets/Home/NoRank.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/NoRank.imageset/NoRank.pdf
  Projects/WeQuiz/Resources/Assets.xcassets/Home/SilverGrade.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/SilverGrade.imageset/SilverGrade.pdf
  Projects/WeQuiz/Resources/Assets.xcassets/Home/profileImage.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/profileImage.imageset/profileImage.pdf
  Projects/WeQuiz/Sources/Home/Answer/AnswerListContainer.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerListRow.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerListRowDataStore.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerPercentView.swift
  Projects/WeQuiz/Sources/Home/FriendRank/FriendRankView.swift
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
  Projects/WeQuiz/Sources/Home/QuizDetail/QuizDetailView.swift
  Projects/WeQuiz/Sources/Home/QuizGroup/QuizGroupView.swift
  Projects/WeQuiz/Sources/Main/WeQuizApp.swift
  Projects/WeQuiz/Sources/Quiz/Answer/AlphabetCircleView.swift
  Projects/WeQuiz/Sources/Quiz/Answer/InputAnswerView.swift
Labels: :white_check_mark: Accepted

#103 [DA] 회원가입 QA 내용 반영
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQButton.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQInputField.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQTextField/WQLimitCharacterTextField.swift
  Projects/Home/Targets/HomeKit/Sources/Network/Models/FriendRankResultModel.swift
  Projects/Home/Targets/HomeKit/Sources/Network/Models/QuizDetailResultModel.swift
  Projects/Home/Targets/HomeKit/Sources/Network/ReponseModel/QuizGroupResponseModel.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendRankConfigurator.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendRankDataStore.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendRankInteractor.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendRankModel.swift
  Projects/Home/Targets/HomeUI/Sources/FriendRank/FriendRankPresenter.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomeConfigurator.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomeDataStore.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomeInteractor.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomeModel.swift
  Projects/Home/Targets/HomeUI/Sources/Home/HomePresenter.swift
  Projects/Home/Targets/HomeUI/Sources/QuizDetail/QuizDetailConfigurator.swift
  Projects/Home/Targets/HomeUI/Sources/QuizDetail/QuizDetailDataStore.swift
  Projects/Home/Targets/HomeUI/Sources/QuizDetail/QuizDetailInteractor.swift
  Projects/Home/Targets/HomeUI/Sources/QuizDetail/QuizDetailModel.swift
  Projects/Home/Targets/HomeUI/Sources/QuizDetail/QuizDetailPresenter.swift
  Projects/Home/Targets/HomeUI/Sources/QuizGroup/QuizGroupConfigurator.swift
  Projects/Home/Targets/HomeUI/Sources/QuizGroup/QuizGroupDataStore.swift
  Projects/Home/Targets/HomeUI/Sources/QuizGroup/QuizGroupInteractor.swift
  Projects/Home/Targets/HomeUI/Sources/QuizGroup/QuizGroupModel.swift
  Projects/Home/Targets/HomeUI/Sources/QuizGroup/QuizGroupPresenter.swift
  Projects/WeQuiz/Derived/Sources/TuistAssets+WeQuiz.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/authentication_finish.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/authentication_finish.imageset/authentication_finish.png
  Projects/WeQuiz/Sources/Authentication/AuthManger.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputView.swift
  Projects/WeQuiz/Sources/Authentication/SignUp/SignUpFinishView.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputModel.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputPresenter.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputView.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputViewModel.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputModel.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputPresenter.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#106 ♻️ Home - QA
  Projects/WeQuiz/Derived/Sources/TuistAssets+WeQuiz.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerListContainer.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerListRow.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerListRowDataStore.swift
  Projects/WeQuiz/Sources/Home/Answer/AnwerList.swift
  Projects/WeQuiz/Sources/Main/WeQuizApp.swift
Labels: :white_check_mark: Accepted

#107 [DA] 문제 풀기 도메인 수정
  Projects/WeQuiz/Derived/Sources/TuistAssets+WeQuiz.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/quiz_result_01.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/quiz_result_02.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/quiz_result_03.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/quiz_result_04.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/quiz_result_05.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_background.imageset/quiz_solve_background.svg
  Projects/WeQuiz/Sources/Main/ContentView.swift
  Projects/WeQuiz/Sources/Main/MainNavigator.swift
  Projects/WeQuiz/Sources/Main/WeQuizApp.swift
  Projects/WeQuiz/Sources/Quiz/Models/QuizModel.swift
  Projects/WeQuiz/Sources/Quiz/Network/ResponseModel/QuizResponseModel.swift
  Projects/WeQuiz/Sources/Quiz/QuizResult/QuizResultView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizDataStore.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizInteractor.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizNavigator.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizPresenter.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroViewModel.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/SolveQuizAnswerView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/SolveQuizUserNameInputView.swift
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#108 [DA] 회원가입 도메인 동작 수정
  Projects/WeQuiz/Derived/Sources/TuistAssets+WeQuiz.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/authentication_onboarding_background.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/authentication_onboarding_background.imageset/authentication_onboarding_background.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/authentication_onboarding_logo.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/authentication_onboarding_logo.imageset/authentication_onboarding_logo.png
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/authentication_onboarding_logo.imageset/authentication_onboarding_logo@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Authentication/Onboarding/authentication_onboarding_logo.imageset/authentication_onboarding_logo@3x.png
  Projects/WeQuiz/Sources/Authentication/OnboardingView.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputModel.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputPresenter.swift
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#109 [DA] :bulb: API 요청시 디바이스에 저장된 토큰 사용하도록 변경
  Projects/WeQuiz/Sources/Core/Network/NetworkRequestable.swift
  Projects/WeQuiz/Sources/Home/Network/Service/HomeAPI.swift
  Projects/WeQuiz/Sources/Quiz/Network/Service/QuizAPI.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#110 [DA] :bulb: 비회원인 경우 임시 토큰 발급받아서 퀴즈 풀도록 변경
  Projects/WeQuiz/Sources/Core/Network/NetworkRequestable.swift
  Projects/WeQuiz/Sources/Quiz/Network/RequestModel/QuizRequestModel.swift
  Projects/WeQuiz/Sources/Quiz/Network/ResponseModel/QuizResponseModel.swift
  Projects/WeQuiz/Sources/Quiz/Network/Service/QuizAPI.swift
  Projects/WeQuiz/Sources/Quiz/Network/Service/QuizService.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizInteractor.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizNavigator.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/SolveQuizUserNameInputView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#112 [DA] 전체 QA - 상훈 1️⃣
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQTopBar.swift
  Projects/DesignSystem/Targets/DesignSystemUI/Sources/Component/WQTopBarPreview.swift
  Projects/WeQuiz/Derived/Sources/TuistAssets+WeQuiz.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Home/home_logo.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/home_logo.imageset/home_logo.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Make/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Make/quiz_make_success.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Make/quiz_make_success.imageset/quiz_make_success.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Make/quiz_make_success.imageset/quiz_make_success@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Make/quiz_make_success.imageset/quiz_make_success@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/img_success.imageset/img_success.png
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
  Projects/WeQuiz/Sources/Quiz/QuizCompletion/QuizCompletionView.swift
  Projects/WeQuiz/Sources/Quiz/QuizResult/QuizResultView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/SolveQuizAnswerView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/SolveQuizUserNameInputView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#120 :bulb: 문제 만들기 - UI QA (#89)
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizDataStore.swift
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizView.swift
  Projects/WeQuiz/Sources/Quiz/Models/QuizModel.swift
  Projects/WeQuiz/Sources/Quiz/Question/QuestionView.swift
Labels: :white_check_mark: Accepted, :hatched_chick: sohy

#116 [DA] 전체 QA - 상훈 2️⃣
  Projects/DesignSystem/Derived/Sources/TuistAssets+DesignSystemKit.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Resources/Assets.xcassets/colors/opacity/Black.colorset/Contents.json
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Colors.swift
  Projects/DesignSystem/Targets/DesignSystemKit/Sources/Components/WQModal.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/quiz_result_01.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/quiz_result_01.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/quiz_result_01@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_01.imageset/quiz_result_01@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/quiz_result_02.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/quiz_result_02.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/quiz_result_02@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_02.imageset/quiz_result_02@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/quiz_result_03.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/quiz_result_03.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/quiz_result_03@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_03.imageset/quiz_result_03@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/quiz_result_04.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/quiz_result_04.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/quiz_result_04@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_04.imageset/quiz_result_04@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/quiz_result_05.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/quiz_result_05.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/quiz_result_05@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Result/quiz_result_05.imageset/quiz_result_05@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_background.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_background.imageset/quiz_solve_background.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_background.imageset/quiz_solve_background.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_background.imageset/quiz_solve_background@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_background.imageset/quiz_solve_background@3x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_thumbnail.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_thumbnail.imageset/quiz_solve_thumbnail.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_thumbnail.imageset/quiz_solve_thumbnail.svg
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_thumbnail.imageset/quiz_solve_thumbnail@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Quiz/Solve/quiz_solve_thumbnail.imageset/quiz_solve_thumbnail@3x.png
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputView.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputView.swift
  Projects/WeQuiz/Sources/Core/DynamicLinks.swift
  Projects/WeQuiz/Sources/Home/FriendRank/FriendRankRow.swift
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
  Projects/WeQuiz/Sources/Quiz/QuizCompletion/QuizCompletionView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#118 [DA] 문제풀기 플로우 점검 및 디자인 수정
  Projects/WeQuiz/Sources/Quiz/QuizResult/QuizResultView.swift
  Projects/WeQuiz/Sources/Quiz/QuizResult/View+/QuizResultRankView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizDataStore.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/SolveQuizAnswerView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#119 [DA] :bulb: 회원가입 로딩중에 progressView 추가
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputModel.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputPresenter.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputView.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputViewModel.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputModel.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputPresenter.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputView.swift
  Projects/WeQuiz/Sources/Authentication/UserInformationInput/UserInformationInputViewModel.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputModel.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputPresenter.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputView.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputViewModel.swift
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#122 [DA] :bulb: 로그아웃 기능 구현 (#121)
  Projects/WeQuiz/Sources/Authentication/AuthManger.swift
  Projects/WeQuiz/Sources/Authentication/OnboardingView.swift
  Projects/WeQuiz/Sources/Authentication/SignUp/SignUpFinishView.swift
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
  Projects/WeQuiz/Sources/Main/WeQuizApp.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#124 💡 Home - Indicator 뷰 및 뷰 세부사항 조정
  Projects/DesignSystem/Derived/Sources/TuistAssets+DesignSystemKit.swift
  Projects/WeQuiz/Sources/Home/Answer/AnswerListRow.swift
  Projects/WeQuiz/Sources/Home/Answer/AnwerList.swift
  Projects/WeQuiz/Sources/Home/Home/HomeConfigurator.swift
  Projects/WeQuiz/Sources/Home/Home/HomeDataStore.swift
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
  Projects/WeQuiz/Sources/Home/Network/Service/HomeAPI.swift
  Projects/WeQuiz/Sources/Home/QuizDetail/QuizDetailConfigurator.swift
  Projects/WeQuiz/Sources/Home/QuizDetail/QuizDetailDataStore.swift
  Projects/WeQuiz/Sources/Home/QuizDetail/QuizDetailView.swift
  Projects/WeQuiz/Sources/Main/WeQuizApp.swift
Labels: :white_check_mark: Accepted

#125 [DA] 네트워크 에러 시 토스트 노출
  Projects/DesignSystem/Derived/Sources/TuistAssets+DesignSystemKit.swift
  Projects/WeQuiz/Sources/Authentication/AuthManger.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputModel.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputView.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputModel.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputPresenter.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputView.swift
  Projects/WeQuiz/Sources/Authentication/VerificationCode/VerificationCodeInputViewModel.swift
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizInteractor.swift
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizModel.swift
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizPresenter.swift
  Projects/WeQuiz/Sources/Quiz/MakeQuiz/MakeQuizView.swift
  Projects/WeQuiz/Sources/Quiz/Network/Service/QuizAPI.swift
  Projects/WeQuiz/Sources/Quiz/Network/Service/QuizService.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizDataStore.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizInteractor.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizModel.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizPresenter.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/SolveQuizView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroView.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroViewModel.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/RemovedQuizView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#126 [DA] 문제 상세에서 문제 공유하기 기능 연결
  Projects/DesignSystem/Derived/Sources/TuistAssets+DesignSystemKit.swift
  Projects/WeQuiz/Sources/Home/QuizDetail/QuizDetailView.swift
  Projects/WeQuiz/Sources/Quiz/QuizCompletion/QuizCompletionView.swift
  Projects/WeQuiz/Sources/Quiz/QuizResult/QuizResultView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted

#127 :recycel: Home - RankView 이미지 에러 수정
  Projects/WeQuiz/Sources/Home/FriendRank/FriendRankRow.swift
Labels: :white_check_mark: Accepted

#128 [DA] 홈 화면 네트워크 요청, 결과 받을 때 모두 인티케이터 표시, 삭제 하도록 변경
  Projects/WeQuiz/Derived/Sources/TuistAssets+WeQuiz.swift
  Projects/WeQuiz/Resources/Assets.xcassets/Home/home_empty_question.imageset/Contents.json
  Projects/WeQuiz/Resources/Assets.xcassets/Home/home_empty_question.imageset/home_empty_question.png
  Projects/WeQuiz/Resources/Assets.xcassets/Home/home_empty_question.imageset/home_empty_question@2x.png
  Projects/WeQuiz/Resources/Assets.xcassets/Home/home_empty_question.imageset/home_empty_question@3x.png
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputInteractor.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputModel.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputPresenter.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputView.swift
  Projects/WeQuiz/Sources/Authentication/PhoneNumberInput/PhoneNumberInputViewModel.swift
  Projects/WeQuiz/Sources/Authentication/SignUp/SignUpFinishView.swift
  Projects/WeQuiz/Sources/Home/FriendRank/FriendRankRow.swift
  Projects/WeQuiz/Sources/Home/Home/HomeInteractor.swift
  Projects/WeQuiz/Sources/Home/Home/HomeModel.swift
  Projects/WeQuiz/Sources/Home/Home/HomePresenter.swift
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
  Projects/WeQuiz/Sources/Home/Network/ReponseModel/QuizGroupResponseModel.swift
  Projects/WeQuiz/Sources/Main/WeQuizApp.swift
  Projects/WeQuiz/Sources/Quiz/SolveQuiz/View+/Intro/SolveQuizIntroView.swift
Labels: :whale: szzang, :zap: ASAP, :clock1: In Review

#129 [DA] :bulb: 회원탈퇴 기능 구현
  Projects/DesignSystem/Derived/Sources/TuistAssets+DesignSystemKit.swift
  Projects/WeQuiz/Sources/Authentication/AuthManger.swift
  Projects/WeQuiz/Sources/Authentication/OnboardingView.swift
  Projects/WeQuiz/Sources/Home/Home/HomeView.swift
Labels: :whale: szzang, :zap: ASAP, :white_check_mark: Accepted
